### ISSUE TITLE
Suggestion: use multiprocessing instead of multithreading to increase performance

### ISSUE THREAD

**Issue by laundmo** [CardinalPanda/dandere2x#13]
hello again

i briefly looked through the code and noticed you were using multithreading
*this is not the best you can do* while multithreading certainly is a improvement over normal python for IO tasks like website requests, its better to use multiprocessing for processor hungry tasks! why? cause multithreading isnt paralell!

article about it: https://medium.com/contentsquare-engineering-blog/multithreading-vs-multiprocessing-in-python-ece023ad55a
>*In Multithreading, threads run in parallel.*
>
>    ❌ FALSE !
>
> ->   Actually in a ThreadPool, only one thread is being executed at any given time t.

i hope im not bothering too much

**Comment by CardinalPanda** [comment]
Good proposal, I'm not gonna address this immediately as Python isn't the bottleneck of Dandere2x at the moment (Dandere2x-Cpp needs work)

I'll leave this open to remind myself moving forward.

**Comment by laundmo** [comment]
it may not be the bottleneck right now, but since i assume dandere2x-cpp is started from python, make sure yo ustart that in a new process and not  the current python one, otherwise it might be negativley affected. (i dont know how running the -cpp from python works, just saying)

**Comment by CardinalPanda** [comment]
> it may not be the bottleneck right now, but since i assume dandere2x-cpp is started from python, make sure yo ustart that in a new process and not the current python one, otherwise it might be negativley affected. (i dont know how running the -cpp from python works, just saying)

Gotcha. I'll be further commenting everything out once I finished a midterm tomorrow, so if you want to audit everything I hope to have the code fully documented by the end of the weekend

**Comment by Tremeschin** [comment]
A multiprocessing Python implementation looks juicy at first until you take a look at few things:


1) As aka said, Python isn't really a bottleneck as a whole.

2) With the current internal path system of the files, it'll mess up with basically everything.

3) It'll use more memory depending on the level of multiprocessing (not a real concern since it's not massive).

4) For the CPP part, it's usually miles away from waifu2x and miles away behind ffmpeg's subprocess compression so not a real necessity of multiprocessing here, however the CPP is programmed to use more than one core of the CPU on the block matching algorithm.


However I'll keep this in mind for future research because with the current ffmpeg encode pipe Python is being used a lot more on loading/saving images from arrays at max quality.
