### ISSUE TITLE
harddrive usage really high

### ISSUE THREAD

**Issue by laundmo** [CardinalPanda/dandere2x#15]
hey there,
i noticed that especialyl for larger videos the harddrive usage is really high. so high in fact that i had to abor because my harddrive was full 👎 

there appear to be too many versions of a image saved. for example you could delete the input image and the original image once the upscaled one is done

also, the debug images could be deleted once they are used (maybe have a config setting for this)

i hope theres something that can be done about this

**Comment by CardinalPanda** [comment]
low hard-drive usage is definitely an option for the future. I would need to check out how memory it could theoretically save during runtime

**Comment by Tremeschin** [comment]
@laundmo a somewhat half fix for this is coming soon (tm). It's on my fixes&hacks branch on my fork as for today if you want to check it out. 

I managed to pipe the merged images directly into ffmpeg without writing them to disk, this saves tons of spaces by only having the first "merged" image into the merged dir.

I argued with aka_katto if it was posible to go even beyond only using pipe in the merged stuff, the idea is on the table tho', not sure how it'll go.

I can say for sure it'll not be that easy of a task because the way dandere2x works internally.

I thought about making a temporary ramdisk (not sure how would work on Windows) and do what you said, delete the unused files and only write N frames ahead of the piping thread.

Welp, anyways, it's half fixed by now the disk usage.
